//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.AuthService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/AuthService")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthService.IAuthService")]
    public interface IAuthService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/GetExemplo", ReplyAction="http://tempuri.org/IAuthService/GetExemploResponse")]
        string GetExemplo(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/GetExemplo", ReplyAction="http://tempuri.org/IAuthService/GetExemploResponse")]
        System.Threading.Tasks.Task<string> GetExemploAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/GetUserDescription", ReplyAction="http://tempuri.org/IAuthService/GetUserDescriptionResponse")]
        string GetUserDescription(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/GetUserDescription", ReplyAction="http://tempuri.org/IAuthService/GetUserDescriptionResponse")]
        System.Threading.Tasks.Task<string> GetUserDescriptionAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/SetUserDescription", ReplyAction="http://tempuri.org/IAuthService/SetUserDescriptionResponse")]
        string SetUserDescription(string login, string password, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/SetUserDescription", ReplyAction="http://tempuri.org/IAuthService/SetUserDescriptionResponse")]
        System.Threading.Tasks.Task<string> SetUserDescriptionAsync(string login, string password, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/GetUsers", ReplyAction="http://tempuri.org/IAuthService/GetUsersResponse")]
        Website.AuthService.User[] GetUsers(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/GetUsers", ReplyAction="http://tempuri.org/IAuthService/GetUsersResponse")]
        System.Threading.Tasks.Task<Website.AuthService.User[]> GetUsersAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/GetUsersByCertificate", ReplyAction="http://tempuri.org/IAuthService/GetUsersByCertificateResponse")]
        Website.AuthService.User[] GetUsersByCertificate(string base64pkcs7Signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/GetUsersByCertificate", ReplyAction="http://tempuri.org/IAuthService/GetUsersByCertificateResponse")]
        System.Threading.Tasks.Task<Website.AuthService.User[]> GetUsersByCertificateAsync(string base64pkcs7Signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/SetUserCertificate", ReplyAction="http://tempuri.org/IAuthService/SetUserCertificateResponse")]
        string SetUserCertificate(string login, string password, string base64pkcs7Signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/SetUserCertificate", ReplyAction="http://tempuri.org/IAuthService/SetUserCertificateResponse")]
        System.Threading.Tasks.Task<string> SetUserCertificateAsync(string login, string password, string base64pkcs7Signature);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthServiceChannel : Website.AuthService.IAuthService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthServiceClient : System.ServiceModel.ClientBase<Website.AuthService.IAuthService>, Website.AuthService.IAuthService {
        
        public AuthServiceClient() {
        }
        
        public AuthServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetExemplo(string input) {
            return base.Channel.GetExemplo(input);
        }
        
        public System.Threading.Tasks.Task<string> GetExemploAsync(string input) {
            return base.Channel.GetExemploAsync(input);
        }
        
        public string GetUserDescription(string login) {
            return base.Channel.GetUserDescription(login);
        }
        
        public System.Threading.Tasks.Task<string> GetUserDescriptionAsync(string login) {
            return base.Channel.GetUserDescriptionAsync(login);
        }
        
        public string SetUserDescription(string login, string password, string description) {
            return base.Channel.SetUserDescription(login, password, description);
        }
        
        public System.Threading.Tasks.Task<string> SetUserDescriptionAsync(string login, string password, string description) {
            return base.Channel.SetUserDescriptionAsync(login, password, description);
        }
        
        public Website.AuthService.User[] GetUsers(string login, string password) {
            return base.Channel.GetUsers(login, password);
        }
        
        public System.Threading.Tasks.Task<Website.AuthService.User[]> GetUsersAsync(string login, string password) {
            return base.Channel.GetUsersAsync(login, password);
        }
        
        public Website.AuthService.User[] GetUsersByCertificate(string base64pkcs7Signature) {
            return base.Channel.GetUsersByCertificate(base64pkcs7Signature);
        }
        
        public System.Threading.Tasks.Task<Website.AuthService.User[]> GetUsersByCertificateAsync(string base64pkcs7Signature) {
            return base.Channel.GetUsersByCertificateAsync(base64pkcs7Signature);
        }
        
        public string SetUserCertificate(string login, string password, string base64pkcs7Signature) {
            return base.Channel.SetUserCertificate(login, password, base64pkcs7Signature);
        }
        
        public System.Threading.Tasks.Task<string> SetUserCertificateAsync(string login, string password, string base64pkcs7Signature) {
            return base.Channel.SetUserCertificateAsync(login, password, base64pkcs7Signature);
        }
    }
}
