//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsClient.TSAService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TSAService.ITSA")]
    public interface ITSA {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITSA/GetTimestamp", ReplyAction="http://tempuri.org/ITSA/GetTimestampResponse")]
        string GetTimestamp(string base64Hash);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITSAChannel : WindowsClient.TSAService.ITSA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TSAClient : System.ServiceModel.ClientBase<WindowsClient.TSAService.ITSA>, WindowsClient.TSAService.ITSA {
        
        public TSAClient() {
        }
        
        public TSAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TSAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TSAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TSAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetTimestamp(string base64Hash) {
            return base.Channel.GetTimestamp(base64Hash);
        }
    }
}
